### ISSUE TITLE
Help me build launcher source code

### ISSUE THREAD

**Issue by bonequixo** [PascalCorpsman/fpc_atomic#5]
Hi, I made everything described in the Readme, but I'm getting an error when running or building the atomic launcher:
`sdlstdinc.inc(43,34) Error: Syntax error, ")" expected but ":" found`

OS: Ubuntu 24.04
IDE: Lazarus 3.6
FPC: 3.2.2

Can you help me?
![Screenshot from 2024-11-29 06-38-35](https://github.com/user-attachments/assets/7a65c79c-88a6-4133-a53d-3371f22adabc)
![Screenshot from 2024-11-29 06-38-45](https://github.com/user-attachments/assets/1e65723e-c146-430f-8b54-b7b848b5fc54)

**Comment by PascalCorpsman** [comment]
Hello,
and cool that you are trying to compile the code, if you did because you want to use the SDL Feature, the plan is to release the new sdl version around January the 6. in 2025.

At first, the code you share is not "writen" by me, so in general this is a issue in the https://github.com/PascalGameDevelopment/SDL2-for-Pascal project.

But in order to help you anyway i looked into the code and it seems that your jedi.inc is setting the defines wrong, on my machine:

Linux Mint: 21.3
Lazarus: 3.99
FPC: 3.2.2

The HAS_Int64 flag is set. So please check why this flag is not set on your machine..

**Comment by bonequixo** [comment]
Thank you for replying!

`because you want to use the SDL Feature`
Is it optional?

`Lazarus: 3.99`
Is that right? I can't find a 3.99 version, neither on https://download.lazarus-ide.org/ nor on https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/
There's a 4.0 version available, but it's a release candidate.

**Comment by PascalCorpsman** [comment]
By default the game does not need SDL, it is only included for gamepad support. So if you do not want to use a Joystick or gamepad its totally fine to download the files from https://github.com/PascalCorpsman/fpc_atomic/tree/main/bin and run the game without the need to compile it.

Lazarus 3.99 is my develop version, using 3.6 is totally fine and should not be an issue here.

Please open the jedi.inc file and see why the code disables the definition of the has_INT64 define, to see whats causing the issue on your side.

**Comment by bonequixo** [comment]
I've made a lot of changes in the project control files (*.lpi) and other stuff. There's a lot of references to files in many "Sample" folders and I pointed all of them to the units folder. Now all projects are building sucessfully, except "launcher/atomic_launcher.lpi".

About the jedi.inc issue, I've made the following changes before copying the files to the "units" folder:
- at the "synapse" files, renamed "jedi.inc" to "synapse_jedi.inc" and replaced references in files.
- at the "SDL2-for-Pascal" files, renamed "jedi.inc" to "sdl2_jedi.inc" and replaced references in files.

When building the "client" project (fpc_atomic/client/fpc_atomic.lpi) Lazarus reports the following error:
`Warning: linker: /usr/bin/ld: cannot find -lbass: No such file or directory`
Solution: copy "bass24-linux/libs/x86_64/libbass.so" to "/usr/lib/" (or equivalent in the path).

Now I'm stuck at the "launcher/ulauncher.pas" file, where I can't find the following objects:
TJSONArray
TJSONNode
TJSONNodeObj
TJSONObj
TJSONParser
TJSONValue

Some related classes (like TJSONArray) are defined in "uJSON.pas", but not the others. I found a number of different versions of this file out there, but it looks like the lastest version is at https://sourceforge.net/projects/is-webstart/. Can you confirm it really is the version you're using or provide your version?

**Comment by PascalCorpsman** [comment]
Wow, it seems that i really have to adjust my documentations.

1. You figured out that synapse und sdl both contain a jedi.inc -> they both should lay in different folders (as you could see when looking into my .lpi configuration). Or as you did rename the jedi.inc and all references.
2. The need of installing bass is right and i missed that one too, sorry for that.
3. i wrote my own JSON interpreter / parser and it seems that my release script did not copy the file into the git repository. I will fix that as soon as i have access to my sources. For now you can use the version from my [examples](https://github.com/PascalCorpsman/Examples/blob/master/data_control/uJSON.pas) repository. 

It seems that you are the very first person (other than me) that tries to compile my code, sorry for all that missing files and bad documentation, i will try my best to fix that for future users. And very thanks that you stay tuned (y)

**Comment by PascalCorpsman** [comment]
Finally i was able to get access to a Windows machine test / compile 
- the ai
- the client
- the launcher
- the server
- the cd_data_extractor (+ no gui version)

Updated the code with the commits 1cb22bacf61674272f18adf19612acf1f01e7d87 and 5dee1eb401b43c9d22fa8fadce991c44291d431d and c126bd15fd31fcabac59d239f55392ed60f80f85 and 28cc7c8cd7f1c86d115db6500ce50cdde7624677 to improve the guides and add missing files.

I will close the issue now as it should be solved. If you have any left questions please don't hesitate to reopen it or create a new one.
